export const QUERY_KEYS = {
  USER: ["userProfile"],
  POSTS: ["posts"],
  COMMENTS: ["comments"],
  FAVORITE_TOURS: ["favoriteTours"],
  FAVORITE_TOUR_CHECK: (tourId: string) => ["favoriteTours", "check", tourId],
  REVIEWS: ["reviews"],
  REVIEWS_BY_TOUR: (tourId: string) => ["reviews", "tour", tourId],
  MY_REVIEWS: ["reviews", "my-reviews"],
  REVIEW: (reviewId: string) => ["reviews", reviewId],
  TOURS: ["tours"],
  TOURS_AVAILABLE: ["tours", "available"],
  TOUR: (tourId: string) => ["tour", tourId],
  TOURS_SEARCH: (keyword: string) => ["tours", "search", keyword],
};
